### ISSUE TITLE
k8s plugin CF error

### ISSUE THREAD

**Issue by hantden** [madcore-ai/plugins#36]
2017-02-01 11:33:03,833 [INFO] madcore.libs.cloudformation: [MADCORE-K8sCluster] Stack does not exists, creating it...
2017-02-01 11:33:04,257 [ERROR] madcore: An error occurred (ValidationError) when calling the CreateStack operation: Template format error: JSON not well-formed. (line 82, column 23)
2017-02-01 11:33:04,259 [DEBUG] madcore: Got an error: An error occurred (ValidationError) when calling the CreateStack operation: Template format error: JSON not well-formed. (line 82, column 23)
2017-02-01 11:33:04,267 [DEBUG] madcore: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/dist-packages/madcore-0.3.7.44+g452228e-py2.7.egg/madcore/cmds/plugins/install.py", line 25, in take_action
    plugin_installed = self.execute_plugin_job(plugin_name, self.plugin_job, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/madcore-0.3.7.44+g452228e-py2.7.egg/madcore/libs/plugins.py", line 233, in execute_plugin_job
    cf_result = executor(plugin_name, sequence, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/madcore-0.3.7.44+g452228e-py2.7.egg/madcore/libs/plugins.py", line 73, in execute_plugin_create_cloudformation_job
    capabilities=job_definition['capabilities']
  File "/usr/local/lib/python2.7/dist-packages/madcore-0.3.7.44+g452228e-py2.7.egg/madcore/libs/cloudformation.py", line 135, in create_stack_if_not_exists
    self.create_stack(stack_name, stack_template_body, stack_params, capabilities=capabilities)
  File "/usr/local/lib/python2.7/dist-packages/madcore-0.3.7.44+g452228e-py2.7.egg/madcore/libs/cloudformation.py", line 113, in create_stack
    Capabilities=capabilities or []
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Template format error: JSON not well-formed. (line 82, column 23)

**Comment by botzill** [comment]
Well, you have an invalid JSON file, check  the cluster.json file via http://jsonlint.com/

**Comment by hantden** [comment]
fixed
